### PR TITLE
Baritone Altoclef 1.18

### PR DESCRIPTION
**Pull request by lolo45654**
My first every pull request, its for 1.18 altoclef (baritone)
Please let me know if i did something wrong.

Btw i have to say that most of the things are from meteorclient developer, and i just added things of altoclef, but i just noticed that if files already exists you dont have to update them so, yeah. ALL of the things are made by meteor developer

### CODE REVIEW

**Comment by wagyourtail** [comment]
I am not a meteorclient dev, they just forked my fork of baritone because I did 1.17 and 1.18 support :upside_down_face: 
and then they applied their patches to make fabric default and some other stuff in https://github.com/gaucho-matrero/baritone/pull/1/commits/515a8ca5c66e0b64a11f3677b0386ce19ec71ef0

for merging (whoever's in charge of that) I'd suggest grabbing the 1.18 branch from upstream and pushing it to this repo. then after changing branches for this pr it should just show the remaining actual changes for altoclef :)

**Comment by lolo45654** [comment]
I'm sorry, i am really new to this thing (Pull requests). I'm just trying to help

**Comment by Bluscream** [comment]
Do you got an artifact for me?

**Comment by TacoTechnica** [comment]
Am merging this separately following wagyourtail's advice, but I appreciate this nonetheless, thank you!

**Pull request closed without merging**
